### ISSUE TITLE
null is not an object (evaluating 'ReactNativeFlurry.initBuilder') while using Expo

### ISSUE THREAD

**Issue by cbanksbi** [flurry/react-native-flurry-sdk#31]
**Describe the bug**
Basically running into this bug when trying to init Flurry in my Expo project. Being that Expo's entry point is essentially App.js I call this method towards the bottom of my file before exporting. Can this package be used with Expo? I've been searching all over and haven't found instructions to use it in unison with it.

**This Bug is About**
- [x] Integration
- [ ] Analytics
- [ ] Messaging/Push
- [ ] Remote Configuration
- [ ] Flurry Website/Dashboard
- [ ] Other

**Environment**
* React Native version: 0.63.2
* react-native-flurry-sdk version: 6.2.0 

**To Reproduce**
1. Happens on build: `expo start`

**App.js**

```
// ...

import Flurry from 'react-native-flurry-sdk';

// ...

new Flurry.Builder()
  .withCrashReporting(true)
  .withLogEnabled(true)
  .withLogLevel(Flurry.LogLevel.DEBUG)
  .build('ANDROID_API_KEY', 'IOS_API_KEY');

export default () => (
  <Provider store={ store }>
     <PersistGate
       loading={ null }
       persistor={ persistor }
      >
      <AppContainer/>
    </PersistGate>
  </Provider>
);
```

**Screenshots**
![image](https://user-images.githubusercontent.com/10405326/105276058-90df1000-5b6e-11eb-9558-e5a95f0f64d1.png)

**Comment by poting-oath** [comment]
@cbanksbi Currently Expo is not supported by our Flurry plugin, and is not tested. We will look into this support.

If you have any suggestion and recommended fix, please also provide it so we can integrate with. Thanks!

**Comment by robertpreoteasa** [comment]
@cbanksbi did you manage to find a solution? We have the same issue on our app and did't find a fix yet.

**Comment by poting-oath** [comment]
@cbanksbi @robertpreoteasa 
Expo does NOT support or manage custom native libraries except their own build-in. I.e., Flurry plugin is a native library that invokes the native Android/iOS modules, and Expo does not support these kinds of native libraries.

You will need to "eject" Expo if you need to extend your apps to use the native libraries.

You can find more info here,
- https://reactnative.dev/docs/environment-setup
  **Caveats**
  Because you don't build any native code when using Expo to create a project, it's not possible to include custom native modules beyond the React Native APIs and components that are available in the Expo client app.
- https://docs.expo.io/introduction/why-not-expo/
  **Native libraries to integrate with proprietary services are usually not included in the SDK**
  Related to the previous point, we typically avoid adding native modules to the SDK if they are tied to external, proprietary services — we can't add something to the SDK just because a few users need it for their app, we have to think of the broader userbase. In these cases developers will want to use the bare workflow, and they can easily migrate to it by ejecting.
- https://docs.expo.io/introduction/managed-vs-bare/
  **Workflow comparison**
  Add custom native code and manage native dependencies => Bare workflow
